const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.video,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.CSV,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.CSV.Acts.ParseCSV,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.SetLooping,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.System.Acts.MoveLayer,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareOpacity
	];
};
self.C3_JsPropNameTable = [
	{BgGame: 0},
	{LogoAnimasi: 0},
	{DeskInformasi: 0},
	{DeskTentang: 0},
	{BG_BankSoal: 0},
	{Browser: 0},
	{PopupSandi: 0},
	{InputSandi: 0},
	{Papan3: 0},
	{Papan4: 0},
	{Papan2: 0},
	{Papan1: 0},
	{PapanLudo: 0},
	{NoUrut: 0},
	{ID_Jalur: 0},
	{TitikJalan: 0},
	{PosisiSekarang: 0},
	{Tim: 0},
	{Skor: 0},
	{AngkaStart: 0},
	{NoUrutPion: 0},
	{SudahPutar: 0},
	{JarakTempuh: 0},
	{Langkah: 0},
	{Pion1: 0},
	{Pion2: 0},
	{Pion3: 0},
	{Pion4: 0},
	{Giliran: 0},
	{Piala1: 0},
	{Piala2: 0},
	{Piala3: 0},
	{Piala4: 0},
	{CharID: 0},
	{PemainID: 0},
	{Pionn1: 0},
	{Pionn2: 0},
	{Pionn3: 0},
	{Pionn4: 0},
	{Pionn5: 0},
	{Pionn6: 0},
	{Pionn7: 0},
	{Pionn8: 0},
	{BarisP1: 0},
	{BarisP2: 0},
	{BarisP3: 0},
	{BarisP4: 0},
	{BgKuis: 0},
	{JawabanA: 0},
	{JawabanB: 0},
	{JawabanC: 0},
	{JawabanD: 0},
	{PapanSkor: 0},
	{PopupFeedback: 0},
	{Shadow: 0},
	{SkorBiru: 0},
	{SkorHijau: 0},
	{SkorKuning: 0},
	{SkorMerah: 0},
	{TeksSoal: 0},
	{TombolA: 0},
	{TombolB: 0},
	{TombolC: 0},
	{TombolD: 0},
	{WadahGambar: 0},
	{WadahVideo: 0},
	{AngkaDadu: 0},
	{Dadu: 0},
	{BGDadu: 0},
	{BGDadu2: 0},
	{ButtonSound: 0},
	{Lanjut: 0},
	{Informasi: 0},
	{Kembali: 0},
	{Masuk: 0},
	{Tween: 0},
	{Mulai: 0},
	{Tentang: 0},
	{Keluar: 0},
	{MainLagi: 0},
	{Lanjutkan: 0},
	{MulaiUlang: 0},
	{BukaGoogleSheet: 0},
	{BukaTutorial: 0},
	{ButtonBankSoal: 0},
	{Login: 0},
	{BingkaiButton: 0},
	{Refresh: 0},
	{"2Player": 0},
	{"3Player": 0},
	{"4Player": 0},
	{A1: 0},
	{A2: 0},
	{A3: 0},
	{A4: 0},
	{JumlahPion: 0},
	{Audio: 0},
	{Mouse: 0},
	{Touch: 0},
	{LogoTambahan: 0},
	{PopUpPause: 0},
	{ButtonPause: 0},
	{PapanHasilAkhir: 0},
	{IkonJuaraP1: 0},
	{IkonJuaraP2: 0},
	{IkonJuaraP3: 0},
	{IkonJuaraP4: 0},
	{AJAX: 0},
	{BankSoal: 0},
	{CSV: 0},
	{KeluargaPion: 0},
	{FamilyPilih: 0},
	{Setting_JumlahPion: 0},
	{Setting_JumlahPemain: 0},
	{Setting_IDLogo: 0},
	{NomorSoal: 0},
	{KunciJawaban: 0},
	{SkorP1: 0},
	{SkorP2: 0},
	{SkorP3: 0},
	{SkorP4: 0},
	{GiliranMenjawab: 0},
	{MasukP1: 0},
	{MasukP2: 0},
	{MasukP3: 0},
	{MasukP4: 0},
	{TimSelesai: 0},
	{UrutanFinish: 0},
	{RankP1: 0},
	{RankP2: 0},
	{RankP3: 0},
	{RankP4: 0},
	{FinalP1: 0},
	{FinalP2: 0},
	{FinalP3: 0},
	{FinalP4: 0},
	{StatusSuara: 0},
	{TargetLangkah: 0},
	{ID_CharP1: 0},
	{ID_CharP2: 0},
	{ID_CharP3: 0},
	{ID_CharP4: 0}
];

self.InstanceType = {
	BgGame: class extends self.ISpriteInstance {},
	LogoAnimasi: class extends self.ISpriteInstance {},
	DeskInformasi: class extends self.ISpriteInstance {},
	DeskTentang: class extends self.ISpriteInstance {},
	BG_BankSoal: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	PopupSandi: class extends self.ISpriteInstance {},
	InputSandi: class extends self.ITextInputInstance {},
	Papan3: class extends self.ISpriteInstance {},
	Papan4: class extends self.ISpriteInstance {},
	Papan2: class extends self.ISpriteInstance {},
	Papan1: class extends self.ISpriteInstance {},
	PapanLudo: class extends self.ISpriteInstance {},
	TitikJalan: class extends self.ISpriteInstance {},
	Pion1: class extends self.ISpriteInstance {},
	Pion2: class extends self.ISpriteInstance {},
	Pion3: class extends self.ISpriteInstance {},
	Pion4: class extends self.ISpriteInstance {},
	Giliran: class extends self.ITextInstance {},
	Piala1: class extends self.ISpriteInstance {},
	Piala2: class extends self.ISpriteInstance {},
	Piala3: class extends self.ISpriteInstance {},
	Piala4: class extends self.ISpriteInstance {},
	Pionn1: class extends self.ISpriteInstance {},
	Pionn2: class extends self.ISpriteInstance {},
	Pionn3: class extends self.ISpriteInstance {},
	Pionn4: class extends self.ISpriteInstance {},
	Pionn5: class extends self.ISpriteInstance {},
	Pionn6: class extends self.ISpriteInstance {},
	Pionn7: class extends self.ISpriteInstance {},
	Pionn8: class extends self.ISpriteInstance {},
	BarisP1: class extends self.ISpriteInstance {},
	BarisP2: class extends self.ISpriteInstance {},
	BarisP3: class extends self.ISpriteInstance {},
	BarisP4: class extends self.ISpriteInstance {},
	BgKuis: class extends self.ISpriteInstance {},
	JawabanA: class extends self.ITextInstance {},
	JawabanB: class extends self.ITextInstance {},
	JawabanC: class extends self.ITextInstance {},
	JawabanD: class extends self.ITextInstance {},
	PapanSkor: class extends self.ISpriteInstance {},
	PopupFeedback: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	SkorBiru: class extends self.ITextInstance {},
	SkorHijau: class extends self.ITextInstance {},
	SkorKuning: class extends self.ITextInstance {},
	SkorMerah: class extends self.ITextInstance {},
	TeksSoal: class extends self.ITextInstance {},
	TombolA: class extends self.ISpriteInstance {},
	TombolB: class extends self.ISpriteInstance {},
	TombolC: class extends self.ISpriteInstance {},
	TombolD: class extends self.ISpriteInstance {},
	WadahGambar: class extends self.ISpriteInstance {},
	WadahVideo: class extends self.IWorldInstance {},
	AngkaDadu: class extends self.ISpriteInstance {},
	Dadu: class extends self.ISpriteInstance {},
	BGDadu: class extends self.ISpriteInstance {},
	BGDadu2: class extends self.ISpriteInstance {},
	ButtonSound: class extends self.ISpriteInstance {},
	Lanjut: class extends self.ISpriteInstance {},
	Informasi: class extends self.ISpriteInstance {},
	Kembali: class extends self.ISpriteInstance {},
	Masuk: class extends self.ISpriteInstance {},
	Mulai: class extends self.ISpriteInstance {},
	Tentang: class extends self.ISpriteInstance {},
	Keluar: class extends self.ISpriteInstance {},
	MainLagi: class extends self.ISpriteInstance {},
	Lanjutkan: class extends self.ISpriteInstance {},
	MulaiUlang: class extends self.ISpriteInstance {},
	BukaGoogleSheet: class extends self.ISpriteInstance {},
	BukaTutorial: class extends self.ISpriteInstance {},
	ButtonBankSoal: class extends self.ISpriteInstance {},
	Login: class extends self.ISpriteInstance {},
	BingkaiButton: class extends self.ISpriteInstance {},
	Refresh: class extends self.ISpriteInstance {},
	_2Player: class extends self.ISpriteInstance {},
	_3Player: class extends self.ISpriteInstance {},
	_4Player: class extends self.ISpriteInstance {},
	A1: class extends self.ISpriteInstance {},
	A2: class extends self.ISpriteInstance {},
	A3: class extends self.ISpriteInstance {},
	A4: class extends self.ISpriteInstance {},
	JumlahPion: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LogoTambahan: class extends self.ISpriteInstance {},
	PopUpPause: class extends self.ISpriteInstance {},
	ButtonPause: class extends self.ISpriteInstance {},
	PapanHasilAkhir: class extends self.ISpriteInstance {},
	IkonJuaraP1: class extends self.ISpriteInstance {},
	IkonJuaraP2: class extends self.ISpriteInstance {},
	IkonJuaraP3: class extends self.ISpriteInstance {},
	IkonJuaraP4: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	BankSoal: class extends self.IArrayInstance {},
	CSV: class extends self.IInstance {},
	KeluargaPion: class extends self.ISpriteInstance {},
	FamilyPilih: class extends self.ISpriteInstance {}
}